"""
Chrome Trace Analyzer — fast-gpt-lab
Parses PyTorch Profiler JSON traces to identify GPU idle times and kernel bottlenecks.
"""
import json
from typing import List, Dict

class TraceAnalyzer:
    """
    Automated inspector for Chrome-formatted Trace JSON files generated by torch.profiler.
    Identifies 'white space' (idle execution blocks) where memory boundaries block the SMs.
    """
    def __init__(self, trace_path: str):
        self.trace_path = trace_path
        with open(trace_path, 'r') as f:
            self.data = json.load(f)

    def extract_gpu_kernels(self) -> List[Dict]:
        """Filters events to extract only GPU executed kernels."""
        gpu_events = []
        for event in self.data.get('traceEvents', []):
            # Cuda related activity
            if event.get('cat') == 'kernel' or 'gpu' in str(event.get('name', '')).lower():
                gpu_events.append(event)
        return gpu_events

    def calculate_gpu_active_time(self) -> float:
        """Calculates total milliseconds the GPU SMs were actively processing."""
        kernels = self.extract_gpu_kernels()
        if not kernels:
            return 0.0
            
        total_dur_us = sum(k.get('dur', 0) for k in kernels)
        return total_dur_us / 1000.0  # ms
